### ISSUE TITLE
Question: Wrapper around Reflex components

### ISSUE THREAD

**Issue by jzoric** [leefsmp/Re-Flex#10]
Hi,
first of all, thanks for the Re-Flex. It's really great.

I want to make the panes hide-able and for this reason I tried with a wrapper around Reflex component.

Idea is to have a wrapper around "ReflexElement", "ReflexSplitter" like:

*Main component*
```
<div className="demo-basic-splitter">
   <ReflexContainer orientation="vertical">
      <Search/>
      <Splitter/>
      <Details/>
   </ReflexContainer>
</div>
```

*Search component*
```
<ReflexElement className="left-pane">
    <div className="pane-content">
        Search component
    </div>
</ReflexElement>
```

*Spliiter component*
```
return (
    <ReflexSplitter/>
)
```

and then to have a onClick event which will show or hide a specific component (e.g. Search, Splitter, Details). Because you are using flex, layout should work. Maybe, also ReflexSplitter can be inside the wrapper component (not in a separate wrapper component).

Problem is, when I use the wrappers Splitter doesn't work.

Is there a way to achieve this? From your point of view, can this be done?
Thanks!

**Comment by leefsmp** [comment]
I'm not sure what is the problem, it should work, I have an example of wrapping ReflexElement in a custom component to add extra logic around it. Take a look at [PaneElement](https://github.com/Autodesk-Forge/forge-rcdb.nodejs/blob/master/src/client/components/PaneManager/PaneElement.js) from [this component](https://github.com/Autodesk-Forge/forge-rcdb.nodejs/tree/master/src/client/components/PaneManager). A live demo is [there](https://forge-rcdb.autodesk.io/configurator?id=57f3739777c879f48ad54a44).

If you simply want to show/hide the components, you could pass a class with "display":"none" to the ReflexElement or splitter. Or you could render the visible elements only being returned by a function, something like below:

`render () {

    return (
      <ReflexContainer orientation={this.props.orientation}>
        { this.renderChildren() }
      </ReflexContainer>
    )
  }`

inside renderChildren add some logic that returns only visible elements in an array...

Do you have a reproducible demo in a repo I can look at?

**Comment by jzoric** [comment]
Here is the basic setup: [react-reflex-playground](https://github.com/jzoric/react-reflex-playground).

When you run `yarn start` 2 panels are shown with the splitter but there are errors in the console and splitter doesn't work. 

Regarding "display":"none", you are right, I do plan to go with that approach.

**Comment by Janpot** [comment]
@jzoric I think you need to make `ReflexElement` and `ReflexSplitter` direct children of `reflexContainer` [here](https://github.com/jzoric/react-reflex-playground/blob/master/src/ReflexDemo.js#L14). I don't think it makes sense to have it another way.

@leefsmp maybe you can show a warning when it finds an element that is not a `ReflexElement` or a `ReflexSplitter`?

**Comment by jzoric** [comment]
@leefsmp  I looked at your examples one more time and found out that the difference is in adding `{...this.props}` on the child component. By adding this it worked. I updated my [react-reflex-playground](https://github.com/jzoric/react-reflex-playground) example.

`ReflexSplitter` behaves differently with `{...this.props}` added but then, in the end, it doesn't need to be a separated component. He can get the `style` from the state and it will work.

I added the toggle functionality on the Search component which does what I want.

Can you give me more details why this works with `{...this.props}` ?

@Janpot 
Your suggestion to throw an error when the child element is not directly a `ReflexElement` or `ReflexSplitter` component will prevent the use case that I want. Right?

**Comment by Janpot** [comment]
@jzoric Indeed. But then I'd argue that a component that has a `<ReflexElement>` without `<ReflexContainer>` is not a self-contained component and therefore an anti-pattern. And anti-patterns are a source of bugs, just like the one you ran into.

I think it's better to structure it this way and make `Search` and `Details` fill whatever space they get so they don't have to be aware of where they are in your application.

```jsz
return (
  <ReflexContainer orientation="vertical">
    <ReflexElement>
      <Search/>
    </ReflexElement>
    <ReflexSplitter/>
    <ReflexElement>
      <Details/>
    </ReflexElement>
  </ReflexContainer>
);
```

**Comment by jzoric** [comment]
@Janpot You are right. `display` on `ReflexElement` can be controlled with the state like: 
```
<ReflexElement className="left-pane" style={{display: this.state.show ? 'block' : 'none'}}>
    <Search hideMe={() => this.toggleSearch()}/>
</ReflexElement>
```
which means that I can just focus on the specific components (e.g `Search`, `Details` ) implementation logic.
Great!

**Comment by leefsmp** [comment]
`ReflexContainer` will [clone its children elements](https://github.com/leefsmp/Re-Flex/blob/master/src/lib/ReflexContainer.jsx#L742) in order to inject custom properties which are needed to control the resizing logic. 

`ReflexSplitter` cannot be wrapped because the `ReflexContainer` needs to know if a child type is a splitter or not in order to handle it properly (you may have 2 contiguous children which are not separated by a splitter). When you wrap a component I didn't find a way to determine the type of that wrapped component. In addition I don't see the use case of wrapping a `ReflexSplitter`: it can be styled purely by custom css and the rest can be handled by events. 

However I don't see wrapping`ReflexElement` as a problem. This allows you to encapsulate some rendering and behaviour logic like illustrated in my example above. In that scenario you need to propagate the injected properties to the `ReflexElement`. You could pass them one by one by looking at their name in the code, but an easier way is to use `{...this.props}` which will blindly pass them to the `ReflexElement`.

**Comment by jmquigley** [comment]
> In addition I don't see the use case of wrapping a ReflexSplitter: it can be styled purely by custom css and the rest can be handled by events.

Here is a use case for this.  I'm using [styled components](https://github.com/styled-components/styled-components) around all elements in my app.  This is basically a wrapper around components that use "css in js".  It provides the ability to use a [dynamic theme](https://www.styled-components.com/docs/advanced#theming), where the CSS can be manipulated programmatically as part of the component.  Here is an example I tried:

```
export const LeftSplitter: any = styled(ReflexSplitter)`
    border-left: 2px solid ${(props: any) => props.theme.backgroundColor} !important;
    border-right: 2px solid ${(props: any) => props.theme.backgroundColor} !important;
    background-color: ${(props: any) => props.theme.borderColor} !important;
    width: 1px !important;
    z-index: unset !important;
`;
```

This would then be used in place of the `ReflexSplitter`.

In this code you can see the borders and background color are set based on the contents of the theme (which can be changed dynamically in the app).  I tried this code, but it doesn't work for the reasons you mentioned above; it styles it properly, but leads to some really funky results when moving/sizing with the splitters due to misapplication of the flex settings.

I can't use static CSS to solve this (at least not without making a bunch of special case static splitter CSS settings).

**Comment by leefsmp** [comment]
I'm not using styled components in my apps but that sounds like a reasonable use case... I will take a closer look at what can be done to support wrapped splitters in an elegant way. Thanks for pointing this out.

**Comment by leefsmp** [comment]
`ReflexSplitter` supports children, so one way I can think of would be to style a child custom component with your dynamic theme... The problem I have is that I don't know how to determine if a given element contains a `ReflexSplitter` or not:

    class SplitterWrapper extends React.Component {
      render() {
         return <ReflexSplitter/>
     }
   } 

   console.log(element.type) ->  SplitterWrapper //how to know it contains an inner ReflexSplitter?

**Comment by leefsmp** [comment]
I pull out [that codepen](https://codepen.io/leefsmp/pen/PORxWV) to prove what I'm saying above, clicking the button will generate a random color and update the theme of the InnerSplitter element:

const Reflex = window['react-reflex']
    const Styled = window['styled']
    
    const {
      ReflexContainer,
      ReflexElement,
      ReflexSplitter
      } = Reflex
    
    const InnerSplitter = Styled.default.div`
        background-color: ${(props) => props.theme.backgroundColor} !important;
        height: 100%;`
    
    class Demo extends React.Component {
      
      constructor (props) {
        super (props)
        this.changeTheme = this.changeTheme.bind(this)
        this.state = {
          theme: {
            backgroundColor: "#FF0000"
          }
        }
      }
      
      changeTheme () {
        const backgroundColor = '#'+Math.floor(Math.random()*16777215).toString(16)
        
        this.setState({
          theme: {
            backgroundColor
          }
        })
      }
      
      render() {
        return (
          <div className="demo">
            <button onClick={this.changeTheme}>
              Update Splitter Theme ...
            </button>
            <ReflexContainer orientation="vertical">
              
              <ReflexElement className="left-pane">
                <div className="pane-content">
                  <label>
                    Left Pane
                  </label>
                </div>
              </ReflexElement>
              
              <ReflexSplitter>
                <InnerSplitter theme={this.state.theme}/>
              </ReflexSplitter>
              
              <ReflexElement className="right-pane">
                <div className="pane-content">
                  <label>
                    Right Pane
                  </label>
                </div>
              </ReflexElement>
            </ReflexContainer>
          </div>
        )
      }
    }
    
    const root = document.getElementById('root')
    
    ReactDOM.render(<Demo/>, root)
