### ISSUE TITLE
cool ! Can you add a default width of the configuration item? 

### ISSUE THREAD

**Issue by wxa1048989080** [leefsmp/Re-Flex#18]
like:
<ReflexElement **defaultSize={150}** minSize={100} maxSize={300}>
   content
</ReflexElement>

**Comment by leefsmp** [comment]
The lib is using flex, so it doesn't support absolute size by default. If you know the size of the parent container, you can specify a "flex" property. For example the container is 500px and you want the element to be 100px, you can use: 
`<ReflexElement flex={0.2}>`

If you don't the size of the container in advance, it's a bit tricky to handle in React because you will be able to compute it only after the initial render. In which case you can use `componentDidMount` find size of the parent, compute the desired flex and pass it as prop to the element. 

I considered adding that feature but I think it will add some overhead to the logic of the container, forcing a re-render when it can be avoided by simply using flex property.

**Comment by wxa1048989080** [comment]
got it thank you! good solution!

**Comment by leefsmp** [comment]
FYI - the fix I did for [Issue #19](https://github.com/leefsmp/Re-Flex/issues/19) now enables using `size` as prop on ReflexElement: 
`<ReflexElement size={150} minSize={100} maxSize={300}>` //OK

**Comment by linmic** [comment]
@leefsmp I just tested your solution with the latest release, the following doesn't work:

```
<ReflexElement
  minSize="500"
  resizeHeight={false}
  onStopResize={this.onStopResize}
  size={750}
>
```

**Comment by leefsmp** [comment]
Works fine on my side, take a look at this [pen](https://codepen.io/leefsmp/pen/eQByqd). You may have done something wrong with the container, can you post a complete example? 

There is no point using `resizeHeight` if you don't have `propagateDimensions={true}`. It is mentioned in the properties documentation: 

> resizeHeight: Allows to control if height will be propagated when propagateDimensions={true}.
> Type: bool. Default value: true.

Hope that helps.
