### ISSUE TITLE
Updating size prop

### ISSUE THREAD

**Issue by KenanYusuf** [leefsmp/Re-Flex#55]
Updating ReflexElement's size does not recalculate the flex of the element

As seen in this demo: https://codesandbox.io/s/zqn73pl40x

**Comment by leefsmp** [comment]
I fixed that behavior in `v2.2.8`. A `direction` array needs to be passed to `ReflexElement` to indicate in which direction the container can attempt to modify the size of the element, it's now  defaulted to `[1]`. You can pass `[-1,1]`if the size can be modified both ways, like in [this example](https://leefsmp.github.io/Re-Flex/index.html#demo6) (the middle pane)

**Comment by KenanYusuf** [comment]
Hey, thanks for the reply.

The way I am trying to achieve the resizing is slightly different; I have tried using the direction prop which *does* cause the panes to resize, but not accurately.

Take a look at:
https://codesandbox.io/s/8zly89z7l0

As you can see, they do resize upon clicking the expand relevant expand button, but not to the right size.

**Comment by leefsmp** [comment]
You should try to use an animation like in the [demo](https://leefsmp.github.io/Re-Flex/index.html#demo6) I created rather than setting the final size directly. The difference is that the element will be resized by a tiny step at each iteration and the final result will be probably more accurate. I don't think I could fix the behavior in your latest sandbox with the current state of the library.

**Comment by KenanYusuf** [comment]
Thanks for taking a look, I will try and implement it in the way you have there.

**Comment by leefsmp** [comment]
Here is a working example, sorry if it's coming a bit late ...

[https://codepen.io/leefsmp/pen/MBgeOG](https://codepen.io/leefsmp/pen/MBgeOG)
