### ISSUE TITLE
Cannot read property 'emit' of undefined

### ISSUE THREAD

**Issue by felix9ia** [leefsmp/Re-Flex#60]
I use Array.map and I drag ReflexSplitter，but get this.

```
   <ReflexContainer orientation="horizontal">
          {
            detail.map((detailItem, index) => {
                return (
                  <React.Fragment key={index}>
                  <ReflexElement minSize={90} className={styles.reflexWrapper} style={{marginBottom: '10px'}}>
                   {/* {this.renderDetailHeader(detailItem, index)} */}
                    <div className={classNames('pane-content', styles.tableWrapper)}>
                        <Table rowKey={detailItem.rowKey} locale={{emptyText: '暂无数据'}} bordered={false} rowSelection = {detailItem.rowSelection} pagination={false} size="middle" columns={detailItem.columns} dataSource={detailItem.list} />
                    </div>
                </ReflexElement>
                <ReflexSplitter/>
                </React.Fragment>
                );
            })
          }
 </ReflexContainer>
```
![image](https://user-images.githubusercontent.com/23549191/44015569-29433562-9f04-11e8-966b-3846ff722d90.png)

**Comment by leefsmp** [comment]
I have no elegant solution for that at the moment unfortunately. The reason you are getting this error is because the container will inject some custom properties to its children, but because the use of `React.Fragment` those properties are no longer passed to element and splitter. 

The best approach would be to migrate the library to use the new React context API but that requires significant changes and testing.

Only workaround I can propose in the current state of the code is the following

`
class FragWorkAround
  extends React.Component {

  constructor () {

    super()

    this.children = [
        {name: 'child1'},
        {name: 'child2'}
    ] 
  }  

  renderChildren () {

    const children = []

    this.children.forEach((child, idx) => {

      children.push (
        <ReflexElement key={'re-'+idx}>
         <div className="handle">
              {child.name}
            </div>
        </ReflexElement>
      )

       // dont render last splitter
      if (idx < this.children.length-1) {
        children.push (
          <ReflexSplitter key={'rs-'+idx}/>
        )
      }
    })

    return children
  }

  render () {

    return (
      <ReflexContainer orientation="horizontal">
        {this.renderChildren()}
      </ReflexContainer>
    )
  }
}
`

Hope that helps. When I get time I will take a look at migrating the internal logic to use context API and see if the lib can support Fragments.

**Comment by felix9ia** [comment]
I see. Thank you. I'll try.

**Comment by felix9ia** [comment]
@leefsmp I see. Thank you. I'll try.

**Comment by taras-shedenko** [comment]
In case you do not want a class:

```
const FragWorkAround = ({ orientation, elements }) =>
  <ReflexContainer orientation={orientation}>
    {elements.reduce((acc, currVal, idx) =>
      idx > 0 ?
        [...[...acc, <ReflexSplitter key={idx+'S'}/>], <ReflexElement key={idx+'E'}/>] :
        [...acc, <ReflexElement key={idx+'E'}/>]
    , [])}
  </ReflexContainer>

```

**Comment by leefsmp** [comment]
I'll close that for now since the two workarounds proposed seem acceptable to me. I'll keep using `React.Fragment` as a nice to have but not easily doable with current implementation of the lib.
