### ISSUE TITLE
SCRIPT1002 error in IE

### ISSUE THREAD

**Issue by InnaKutsik** [leefsmp/Re-Flex#64]
I tried to work with you package in IE 11 but it doesn't work. I see SCRIPT1002 error. Babel and any pollyfill didn't help.
Any ideas as to what might be causing this?
SCRIPT1002  - 
![err](https://user-images.githubusercontent.com/14812602/50851060-6275aa00-1384-11e9-8a76-b9c18e57d745.JPG)

**Comment by vodanh109** [comment]
I also got this problem. Anyone can help to solve this issue

**Comment by leefsmp** [comment]
This should be fixed in v.3.0.8. The [demo](https://leefsmp.github.io/Re-Flex/index.html) is now working on my side in IE11.

If you are using Webpack/Babel to build your application, you need to make sure that [your build supports IE11](https://stackoverflow.com/questions/45212267/syntax-error-in-ie11-with-webpack-babel-and-react).

**Comment by leefsmp** [comment]
I can't help you much unfortunately based on your thin description of the issue and due to the fact it works on my side in IE11. 

You could try to run the demo in dev mode locally and see what is causing the error.
