### ISSUE TITLE
Window Resize Issue with Vertical Reflex Container

### ISSUE THREAD

**Issue by Luxapodular** [leefsmp/Re-Flex#74]
Hi @leefsmp!

We've been running into an issue while using windowResizeAware reflex containers. A live version of our app can be seen at [alpha.wickeditor.com](alpha.wickeditor.com).

For some reason, the reflex container is not properly setting the flex sizes of the elements within *sometimes*.

Here's a mock of the code structure:
```
<ReflexContainer windowResizeAware={true} orientation="horizontal">
  ...
  <ReflexContainer windowResizeAware={true} orientation="vertical">
    <ReflexElement size={50} minSize={50} maxSize={50}> ... </ReflexElement>
    <ReflexElement size={this.state.variableSize1} {..this.resizeFunctions} > ... </ReflexElement>
    <ReflexSplitter {...resizeFunctions} /> 
    <ReflexElement minSize={100} size={this.state.variableSize2} {..this.resizeFunctions}> ...</ReflexElement>
  </ReflexContainer>
...
</ReflexContainer>
```

Here's are images of our app before the window is resized and after.

Before:
<img width="1193" alt="screen shot 2019-02-27 at 2 26 23 pm" src="https://user-images.githubusercontent.com/8699557/53517430-91fb8580-3a9c-11e9-99f4-58a15e8f5135.png">

After:
<img width="786" alt="screen shot 2019-02-27 at 2 26 30 pm" src="https://user-images.githubusercontent.com/8699557/53517460-9fb10b00-3a9c-11e9-9b5d-0cfa41346878.png">

And those same images mocked up:

<img width="1193" alt="screen shot 2019-02-27 at 2 26 23 pm2" src="https://user-images.githubusercontent.com/8699557/53517515-cec77c80-3a9c-11e9-8c79-b4740a9147fb.png">

![screen shot 2019-02-27 at 2 26 30 pm2](https://user-images.githubusercontent.com/8699557/53517516-d1c26d00-3a9c-11e9-9cc1-b67488928849.png)

And a (choppy) gif of it live:

![windowresize](https://user-images.githubusercontent.com/8699557/53517530-de46c580-3a9c-11e9-89f5-499667a62b64.gif)

This issue does *not* seem to happen if the timeline (reflex element 3) is not resized in any way before scaling.

I've verified that the size variables being passed into the Reflex Elements are correct. Any thoughts on what I'm doing wrong here?

**Comment by leefsmp** [comment]
It is strange that issue only occurs if reflex element 3 has been resized at least once. This makes me think that it may not be a bug directly in the resizing logic of the container. I see that you are passing `size` property to each element, but from your snippet I can't tell what value you are passing and how it is computed. Did you make sure that the container is not over-constrained? You could try to let one of the element not constrained by any `size` or `flex`. Also, not related to the problem but just a suggestion, since element 1 is always of fixed size I would style it just with css, this will remove some unnecessary computations from the reflex container. 

If that doesn't help I will have to try a reproducible sample on my side...

**Comment by umairtahiri** [comment]
leefsmp is right

**Comment by leefsmp** [comment]
I'll close that for now as it seems so far to be specific to your app. If it is still an issue and the suggestion above didn't help feel free to provide more details or a full repro sample.

Thanks.
