### ISSUE TITLE
React 16.8.4 - ReflexElement causes Element ref warning

### ISSUE THREAD

**Issue by geeklisted** [leefsmp/Re-Flex#75]
Using latest version of react-reflex with React 16.8.4.

As soon as I embed a <ReflexElement> inside of a container, I am greeted with warning as documented here: https://reactjs.org/warnings/refs-must-have-owner.html

I don't believe it is an issue of duplicate React versions as I have checked and this message only appears if I use ReflexElement.  Code below.

```
render() {
return (
 <ReflexContainer orientation={'horizontal'}>
    <ReflexElement className={'left-pane'}>
         <div className={'pane-content'}>test</div>
    </ReflexElement>
 </ReflexContainer>
)
};
```

**Comment by leefsmp** [comment]
I migrated a test app to that React version and cannot see any similar message, also [this pen](https://codepen.io/leefsmp/pen/WYeMgx) seems to work fine. 

<img width="544" alt="Screen Shot 2019-03-15 at 14 54 00" src="https://user-images.githubusercontent.com/4352502/54436092-308d1500-4732-11e9-92d1-cca86325c4b2.png">

**Comment by geeklisted** [comment]
Thanks for taking the time to investigate.  Does it matter if I am not rendering the ReflexContainer at the top-level of our app, but instead rendered a few levels deep?

**Comment by leefsmp** [comment]
No that should not matter, this is what I'm doing in my app, the reflex container should be like any other react component, it may be rendered at any depth in your component tree. So the most logical reason why you are seing this is the multiple versions of react loaded, make sure you dont have a typo in your import maybe: `import React from 'React'` instead of `import React from 'react'`.

**Comment by leefsmp** [comment]
I'll close that ticket for now as non-reproducible, feel free to add comments if you can spot the problem. Thanks.
