### ISSUE TITLE
Found ReflexContainer with height=0, this will cause invalid behavior

### ISSUE THREAD

**Issue by svanetten1976** [leefsmp/Re-Flex#86]
Hi @leefsmp 
 First of all, thanks for this cool lib. It totally did the trick for us right up until the latest update to NodeJS in our app. For some reason, jumping from Node 10.0.0 to Node 10.16.3 has triggered a pretty bad error. We are running React 16.9 and have a complex interface, in which we are using a Re-Flex interface and saving the layout to localStorage. The issue since we updated NodeJS is that if one side of a two-column resizable interface is closed, I get this error and none of the resizing works from there out: "Found ReflexContainer with height=0, this will cause invalid behavior"

Sure seems like I am doing everything right with the setup, especially given the fact that it was fully working until the Node update. Any ideas? Thanks in advance -- Steve

**Comment by leefsmp** [comment]
What is the relation between Reflex and the node version? Are you doing server-side rendering?

**Comment by svanetten1976** [comment]
@leefsmp we are not doing server-side rendering, I'm actually pretty perplexed by the behavior with the Node update. Due to time constraints, I ended up going with a different solution altogether. There does seem to be a bug or two with this package... as someone else pointed out, the ReflexElement component does not reflect the 'flex' props that are passed into it. Anyways, thanks for replying to me. Its generally a good package, we were just attempting to use it in a very complex application, so that could have been causing issues in general --- Steve

**Comment by leefsmp** [comment]
The error _"Found ReflexContainer with height=0, this will cause invalid behavior"_ is usually caused by invalid css style on the ReflexContainer, which - as the message indicates - causes the DOM element to have a height=0. If that's the case you should try to find a workaround or a trade of for complex layouts. Make sure you include the Reflex css as mentioned in that [previous issue](https://github.com/leefsmp/Re-Flex/issues/84) or replace it by equivalent custom css.

Lastly, thanks for using the lib, I'm aware it's not perfect and may have bugs, so if you can setup a reproducible case for any issue in the future feel free to do so, this way we can make it a bit better.

**Comment by TehAwol** [comment]
I have also encountered this bizarre issue since a React upgrade. Style prop on a reflex-element is completely overwritten and given a width of 0 in my case
