### ISSUE TITLE
String vs Number persistance

### ISSUE THREAD

**Issue by KevinDenys** [leefsmp/Re-Flex#95]
For pull request #94 

In our application we use minSize and maxSize to make sure the panel is not bigger than X, when we use numbers to set the sizes of the other panel it does not work. When using strings it works. See below a small example

When you use numbers the right panel is not correct its much bigger than 0.10. https://codepen.io/kevindenys/pen/GRgBeWM
When using strings the right panel is correct
https://codepen.io/kevindenys/pen/XWJBGMr

**Comment by leefsmp** [comment]
Fixed in `v 3.0.22`: there was a missing check when passing initial `flex` to a `ReflexElement`. The flex was not considered to be constrained when passing a number because the computed flex was identical to the input, whereas when passing a string we had string !== number so it was taken into account. 

You can now pass numbers according to the ts definition. Passing strings may lead to unexpected results. Thanks for reporting that issue, this bug made it a long way without being spotted!

**Comment by KevinDenys** [comment]
Can confirm version 3.0.22 fixes the problem and using numbers now works fine. No need to patch the typescript of "flex" anymore. Thank you!
